# Generated by Django 5.0.3 on 2024-09-12 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Kategoriya')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Tag nomi')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('deskription', models.TextField(blank=True, null=True, verbose_name='Matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasmi')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0, verbose_name='Kurishlar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Saytga chiqarish')),
                ('is_banner', models.BooleanField(default=False, verbose_name='Bannerga chiqarish')),
                ('is_weekly', models.BooleanField(default=False, verbose_name='Haftalik yangilk')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('tag', models.ManyToManyField(to='app.tags', verbose_name='Taglar')),
            ],
        ),
    ]
