# Generated by Django 5.0.3 on 2024-09-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
